# Generated by Django 5.0.14 on 2026-08-21 13:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('whatsapp', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="O número de WhatsApp deve ser inserido no formato: '+5511999999999'. De 9 a 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='WhatsApp')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço de Entrega')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações Internas')),
                ('ativo', models.BooleanField(default=True, verbose_name='Cliente Ativo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_pix', models.CharField(max_length=100, verbose_name='Chave PIX para Recebimento')),
                ('tipo_chave_pix', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('EMAIL', 'E-mail'), ('TELEFONE', 'Telefone'), ('ALEATORIA', 'Chave Aleatória')], default='EMAIL', max_length=20, verbose_name='Tipo da Chave PIX')),
                ('nome_titular', models.CharField(max_length=100, verbose_name='Nome do Titular do PIX')),
                ('cidade_titular', models.CharField(default='São Paulo', max_length=100, verbose_name='Cidade do Titular')),
                ('mensagem_padrao_whatsapp', models.TextField(help_text='Use as chaves: {nome}, {periodo}, {detalhes}, {total}, {chave_pix}, {copia_cola} para preencher dinamicamente na cobrança do WhatsApp.', verbose_name='Mensagem Padrão de Cobrança')),
            ],
            options={
                'verbose_name': 'Configuração Geral',
                'verbose_name_plural': 'Configuração Geral',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Produto')),
                ('categoria', models.CharField(choices=[('DOCE', 'Doce'), ('SALGADO', 'Salgado'), ('BOLO', 'Bolo')], max_length=10, verbose_name='Categoria')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, max_length=10, verbose_name='Preço Unitário')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Imagem do Produto')),
                ('disponivel_hoje', models.BooleanField(default=True, verbose_name='Disponível Hoje')),
                ('limite_diario', models.PositiveIntegerField(default=0, help_text='Defina como 0 para produção ilimitada.', verbose_name='Limite de Produção Diário')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FechamentoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('mes', models.PositiveIntegerField(verbose_name='Mês')),
                ('total_devedor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Devedor')),
                ('pago', models.BooleanField(default=False, verbose_name='Pago')),
                ('data_fechamento', models.DateTimeField(auto_now_add=True, verbose_name='Data do Fechamento')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechamentos', to='caderninho.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Fechamento Mensal',
                'verbose_name_plural': 'Fechamentos Mensais',
                'ordering': ['-ano', '-mes', 'cliente__nome'],
                'unique_together': {('cliente', 'ano', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PREPARANDO', 'Preparando'), ('ENTREGUE', 'Entregue/Registrado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status do Pedido')),
                ('status_financeiro', models.CharField(choices=[('ABERTO', 'Aberto (A Pagar)'), ('PAGO', 'Pago')], default='ABERTO', max_length=20, verbose_name='Status Financeiro')),
                ('taxa_entrega', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Taxa de Entrega')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações do Pedido')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='caderninho.cliente', verbose_name='Cliente')),
                ('fechamento_mensal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='caderninho.fechamentomensal', verbose_name='Fechamento Mensal Associado')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Preço Unitário (Histórico)')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='caderninho.pedido', verbose_name='Pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caderninho.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
    ]
