# Generated by Django 5.0.14 on 2026-08-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caderninho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='senha',
            field=models.CharField(default='', help_text='A senha será criptografada automaticamente ao salvar.', max_length=128, verbose_name='Senha de Acesso'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço (Opcional)'),
        ),
    ]
