# Generated by Django 5.0.14 on 2026-08-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caderninho', '0002_cliente_senha_alter_cliente_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaogeral',
            name='whatsapp_loja',
            field=models.CharField(default='+5511999999999', max_length=20, verbose_name='WhatsApp de Contato da Loja'),
        ),
    ]
